droplet_user: steven

security_sudoers_passwordless: "{{ droplet_user }}"

public_key_location: https://github.com/stevenspasbo.keys

packages:
  - wget
  - curl
  - zsh
  - fish
  - aspell
  - hunspell
  - bash-completion
  - git
  - tmux
  - htop
  - unrar
  - weechat
  # - ack-grep
  # - fortune
  # - cowsay
  # - silversearcher-ag
  # - git
  # - coreutils
  # - diffutils
  # - findutils
  # - binutils
  # - colordiff
  # - elixir
  # - erlang
  # - gcc
  # - g++
  # - gdb
  # - ffmpeg
  # - global
  # - gnu-smalltalk
  # - gradle
  # - hunspell
  # - ispell
  # - llvm
  # - make
  # - maven
  # - mit-scheme
  # - racket
  # - ngrep
  # - nmap
  # - ocaml
  # - pandoc
  # - patchutils
  # - perl
  # - sbcl
  # - scala
  # - screen
  # - socat
  # - stow
  # - sysdig
  # - tree



ntp_timezone: America/Los_Angeles
