---
- hosts: all
  become: yes

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - config.yml
        - local.config.yml

    - name: Install packages
      apt: "name={{ item }} state=latest"
      with_items: "{{ apt_packages | list }}"
      when: apt_packages | length

    - name: Update installed packages
      apt:
        upgrade: dist
